targets:
  main:
    resources:
      RawSerialPort:
        port: "/dev/ttyUSB-sh-main"
        speed: 921600
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver: {}
      ShellDriver:
        prompt: 'root@sparrow-hawk'
        login_prompt: ' login: '
        username: 'root'
